"""
Roadmap — milestone read + progress endpoints.

  GET   /api/generate-roadmap/                  list milestones (optionally
                                                scoped to a role) for the user.
  PATCH /api/generate-roadmap/milestones/{id}   update milestone status.

Milestones are generated by the deep researcher (`POST /api/deep-research/`),
which persists them via `roadmap_generation.service.upsert_role_milestones`.
"""
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException

from app.dependencies.auth import require_user_id
from app.dependencies.database import db_client
from app.roadmap_generation.schemas import (
    MilestoneRowOut,
    MilestoneStatusUpdate,
)

router = APIRouter(prefix="/api/generate-roadmap", tags=["Roadmap"])


@router.get("/")
async def list_milestones(
    target_role_id: Optional[str] = None,
    user_id: str = Depends(require_user_id),
):
    q = (
        db_client.table("milestones")
        .select("*")
        .eq("user_id", user_id)
        .order("target_role_id")
        .order("sort_order")
    )
    if target_role_id:
        q = q.eq("target_role_id", target_role_id)
    resp = q.execute()
    return {"success": True, "milestones": resp.data or []}


@router.patch("/milestones/{milestone_id}", response_model=MilestoneRowOut)
async def update_milestone_status(
    milestone_id: str,
    body: MilestoneStatusUpdate,
    user_id: str = Depends(require_user_id),
):
    cur = (
        db_client.table("milestones")
        .select("id,user_id")
        .eq("id", milestone_id)
        .limit(1)
        .execute()
    )
    if not cur.data:
        raise HTTPException(status_code=404, detail="Milestone not found")
    if cur.data[0].get("user_id") != user_id:
        raise HTTPException(status_code=404, detail="Milestone not found")

    completed_at = (
        datetime.now(timezone.utc).isoformat() if body.status == "completed" else None
    )
    upd = (
        db_client.table("milestones")
        .update({
            "status": body.status,
            "completed_at": completed_at,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        })
        .eq("id", milestone_id)
        .execute()
    )
    if not upd.data:
        raise HTTPException(status_code=500, detail="Update returned no row")
    return MilestoneRowOut(**upd.data[0])
