/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GithubCallbackRouteImport } from './routes/github.callback'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppGithubInsightsRouteImport } from './routes/_app.github-insights'
import { Route as AppGithubRouteImport } from './routes/_app.github'
import { Route as AppGapsRouteImport } from './routes/_app.gaps'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github/callback',
  path: '/github/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppGithubInsightsRoute = AppGithubInsightsRouteImport.update({
  id: '/github-insights',
  path: '/github-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppGithubRoute = AppGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => AppRoute,
} as any)
const AppGapsRoute = AppGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/gaps': typeof AppGapsRoute
  '/github': typeof AppGithubRoute
  '/github-insights': typeof AppGithubInsightsRoute
  '/jobs': typeof AppJobsRoute
  '/profile': typeof AppProfileRoute
  '/roadmap': typeof AppRoadmapRoute
  '/github/callback': typeof GithubCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard': typeof AppDashboardRoute
  '/gaps': typeof AppGapsRoute
  '/github': typeof AppGithubRoute
  '/github-insights': typeof AppGithubInsightsRoute
  '/jobs': typeof AppJobsRoute
  '/profile': typeof AppProfileRoute
  '/roadmap': typeof AppRoadmapRoute
  '/github/callback': typeof GithubCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/gaps': typeof AppGapsRoute
  '/_app/github': typeof AppGithubRoute
  '/_app/github-insights': typeof AppGithubInsightsRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/github/callback': typeof GithubCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/gaps'
    | '/github'
    | '/github-insights'
    | '/jobs'
    | '/profile'
    | '/roadmap'
    | '/github/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/dashboard'
    | '/gaps'
    | '/github'
    | '/github-insights'
    | '/jobs'
    | '/profile'
    | '/roadmap'
    | '/github/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/dashboard'
    | '/_app/gaps'
    | '/_app/github'
    | '/_app/github-insights'
    | '/_app/jobs'
    | '/_app/profile'
    | '/_app/roadmap'
    | '/github/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  GithubCallbackRoute: typeof GithubCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github/callback': {
      id: '/github/callback'
      path: '/github/callback'
      fullPath: '/github/callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/github-insights': {
      id: '/_app/github-insights'
      path: '/github-insights'
      fullPath: '/github-insights'
      preLoaderRoute: typeof AppGithubInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/github': {
      id: '/_app/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof AppGithubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gaps': {
      id: '/_app/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AppGapsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppGapsRoute: typeof AppGapsRoute
  AppGithubRoute: typeof AppGithubRoute
  AppGithubInsightsRoute: typeof AppGithubInsightsRoute
  AppJobsRoute: typeof AppJobsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppGapsRoute: AppGapsRoute,
  AppGithubRoute: AppGithubRoute,
  AppGithubInsightsRoute: AppGithubInsightsRoute,
  AppJobsRoute: AppJobsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRoadmapRoute: AppRoadmapRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  GithubCallbackRoute: GithubCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
